# -*- coding: utf-8 -*-
"""NER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vF1ozuEFSM7cqbx-TSwK5LT4ytpFcXKL
"""

#hugging face
from transformers import pipeline

# Load the NER pipeline with entity grouping
ner_pipeline = pipeline("ner", aggregation_strategy="simple")

# Ask user for input
user_input = input("Enter a sentence: ")

# Run NER
entities = ner_pipeline(user_input)

# Print results
print("\nNamed Entity Recognition Output:\n")
if entities:
    for ent in entities:
        print(f"➤ Entity: {ent['word']} | Label: {ent['entity_group']} | Score: {ent['score']:.2f}")
else:
    print("No named entities found in the sentence.")