# -*- coding: utf-8 -*-
"""Spell_corrector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3DQ6tL55FAIlp5P3J4gBO4WibMJT32i
"""

#embeddings
spell = SpellChecker()

def tokenize(text):
    return text.lower().split()

def correct_word(word, similarity_threshold=0.5):
    # 1. If known word, keep as is
    if word in model:
        return word

    # 2. Try embedding similarity first
    try:
        sims = model.most_similar(word, topn=5)
        best_match, score = sims[0]
        if score > similarity_threshold:
            return best_match
    except:
        pass

    # 3. If embedding fails, fallback to spellchecker
    correction = spell.correction(word)
    if correction != word:
        return correction

    # 4. Lastly, try difflib close match
    alt = get_close_matches(word, model.key_to_index.keys(), n=1, cutoff=0.8)
    if alt:
        return alt[0]

    # 5. If all fails, return original word
    return word

def correct_sentence(sentence):
    words = tokenize(sentence)
    corrected = [correct_word(w) for w in words]
    return " ".join(corrected)

# User input
input_sentence = input("📝 Enter sentence with misspellings: ")
corrected_sentence = correct_sentence(input_sentence)
print("\n✅ Corrected Sentence:", corrected_sentence)